services:
  dev:
    # image: ... の行を削除し、代わりに build: . を追加
    build: .
    volumes:
      # ソースコードの変更を即時反映させるためにvolumesは残します
      - .:/workspaces/web-calculator-app:cached

    # この environment セクションを追加します
    environment:
      # PostgreSQLコンテナに接続するための情報を設定
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      # dbサービスで設定したユーザー名、パスワード、DB名と同じものを設定
      - POSTGRES_USER=user_dev
      - POSTGRES_PASSWORD=password_dev
      - POSTGRES_DB=calculator_db
      # Flaskがアプリケーション（run.py）を見つけるための設定
      - FLASK_APP=run.py
      - FLASK_DEBUG=1

    command: sleep infinity
    networks:
      - app_network
    
    # ポートフォワーディングを追加して、ローカルPCからFlaskアプリにアクセスできるようにします
    ports:
      - "5001:5001"


  db: 
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      # ↓ここの値と、devサービスの値を一致させます
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: password_dev
      POSTGRES_DB: calculator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
