services:
  dev:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - .:/workspaces/web-calculator-app:cached
    command: sleep infinity
    networks:
      - app_network

  db: 
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: password_dev
      POSTGRES_DB: calculator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
